// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ige_sync.proto

#ifndef PROTOBUF_ige_5fsync_2eproto__INCLUDED
#define PROTOBUF_ige_5fsync_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ige {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ige_5fsync_2eproto();
void protobuf_AssignDesc_ige_5fsync_2eproto();
void protobuf_ShutdownFile_ige_5fsync_2eproto();

class SendEpoch;
class Timestamp;
class Geometry;
class Entity;
class Item;
class Sync;

// ===================================================================

class SendEpoch : public ::google::protobuf::Message {
 public:
  SendEpoch();
  virtual ~SendEpoch();

  SendEpoch(const SendEpoch& from);

  inline SendEpoch& operator=(const SendEpoch& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendEpoch& default_instance();

  void Swap(SendEpoch* other);

  // implements Message ----------------------------------------------

  SendEpoch* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendEpoch& from);
  void MergeFrom(const SendEpoch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sec = 1;
  inline bool has_sec() const;
  inline void clear_sec();
  static const int kSecFieldNumber = 1;
  inline ::google::protobuf::int32 sec() const;
  inline void set_sec(::google::protobuf::int32 value);

  // required int32 min = 2;
  inline bool has_min() const;
  inline void clear_min();
  static const int kMinFieldNumber = 2;
  inline ::google::protobuf::int32 min() const;
  inline void set_min(::google::protobuf::int32 value);

  // required int32 hour = 3;
  inline bool has_hour() const;
  inline void clear_hour();
  static const int kHourFieldNumber = 3;
  inline ::google::protobuf::int32 hour() const;
  inline void set_hour(::google::protobuf::int32 value);

  // required int32 day = 4;
  inline bool has_day() const;
  inline void clear_day();
  static const int kDayFieldNumber = 4;
  inline ::google::protobuf::int32 day() const;
  inline void set_day(::google::protobuf::int32 value);

  // required int32 mon = 5;
  inline bool has_mon() const;
  inline void clear_mon();
  static const int kMonFieldNumber = 5;
  inline ::google::protobuf::int32 mon() const;
  inline void set_mon(::google::protobuf::int32 value);

  // required int32 year = 6;
  inline bool has_year() const;
  inline void clear_year();
  static const int kYearFieldNumber = 6;
  inline ::google::protobuf::int32 year() const;
  inline void set_year(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ige.SendEpoch)
 private:
  inline void set_has_sec();
  inline void clear_has_sec();
  inline void set_has_min();
  inline void clear_has_min();
  inline void set_has_hour();
  inline void clear_has_hour();
  inline void set_has_day();
  inline void clear_has_day();
  inline void set_has_mon();
  inline void clear_has_mon();
  inline void set_has_year();
  inline void clear_has_year();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 sec_;
  ::google::protobuf::int32 min_;
  ::google::protobuf::int32 hour_;
  ::google::protobuf::int32 day_;
  ::google::protobuf::int32 mon_;
  ::google::protobuf::int32 year_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_ige_5fsync_2eproto();
  friend void protobuf_AssignDesc_ige_5fsync_2eproto();
  friend void protobuf_ShutdownFile_ige_5fsync_2eproto();

  void InitAsDefaultInstance();
  static SendEpoch* default_instance_;
};
// -------------------------------------------------------------------

class Timestamp : public ::google::protobuf::Message {
 public:
  Timestamp();
  virtual ~Timestamp();

  Timestamp(const Timestamp& from);

  inline Timestamp& operator=(const Timestamp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Timestamp& default_instance();

  void Swap(Timestamp* other);

  // implements Message ----------------------------------------------

  Timestamp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Timestamp& from);
  void MergeFrom(const Timestamp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::int64 time() const;
  inline void set_time(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ige.Timestamp)
 private:
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ige_5fsync_2eproto();
  friend void protobuf_AssignDesc_ige_5fsync_2eproto();
  friend void protobuf_ShutdownFile_ige_5fsync_2eproto();

  void InitAsDefaultInstance();
  static Timestamp* default_instance_;
};
// -------------------------------------------------------------------

class Geometry : public ::google::protobuf::Message {
 public:
  Geometry();
  virtual ~Geometry();

  Geometry(const Geometry& from);

  inline Geometry& operator=(const Geometry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Geometry& default_instance();

  void Swap(Geometry* other);

  // implements Message ----------------------------------------------

  Geometry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Geometry& from);
  void MergeFrom(const Geometry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ige.Geometry)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ige_5fsync_2eproto();
  friend void protobuf_AssignDesc_ige_5fsync_2eproto();
  friend void protobuf_ShutdownFile_ige_5fsync_2eproto();

  void InitAsDefaultInstance();
  static Geometry* default_instance_;
};
// -------------------------------------------------------------------

class Entity : public ::google::protobuf::Message {
 public:
  Entity();
  virtual ~Entity();

  Entity(const Entity& from);

  inline Entity& operator=(const Entity& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Entity& default_instance();

  void Swap(Entity* other);

  // implements Message ----------------------------------------------

  Entity* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Entity& from);
  void MergeFrom(const Entity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ige.Entity)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ige_5fsync_2eproto();
  friend void protobuf_AssignDesc_ige_5fsync_2eproto();
  friend void protobuf_ShutdownFile_ige_5fsync_2eproto();

  void InitAsDefaultInstance();
  static Entity* default_instance_;
};
// -------------------------------------------------------------------

class Item : public ::google::protobuf::Message {
 public:
  Item();
  virtual ~Item();

  Item(const Item& from);

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Item& default_instance();

  void Swap(Item* other);

  // implements Message ----------------------------------------------

  Item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ige.Item)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ige_5fsync_2eproto();
  friend void protobuf_AssignDesc_ige_5fsync_2eproto();
  friend void protobuf_ShutdownFile_ige_5fsync_2eproto();

  void InitAsDefaultInstance();
  static Item* default_instance_;
};
// -------------------------------------------------------------------

class Sync : public ::google::protobuf::Message {
 public:
  Sync();
  virtual ~Sync();

  Sync(const Sync& from);

  inline Sync& operator=(const Sync& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sync& default_instance();

  void Swap(Sync* other);

  // implements Message ----------------------------------------------

  Sync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sync& from);
  void MergeFrom(const Sync& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ige.Geometry geometries = 1;
  inline int geometries_size() const;
  inline void clear_geometries();
  static const int kGeometriesFieldNumber = 1;
  inline const ::ige::Geometry& geometries(int index) const;
  inline ::ige::Geometry* mutable_geometries(int index);
  inline ::ige::Geometry* add_geometries();
  inline const ::google::protobuf::RepeatedPtrField< ::ige::Geometry >&
      geometries() const;
  inline ::google::protobuf::RepeatedPtrField< ::ige::Geometry >*
      mutable_geometries();

  // repeated .ige.Entity entities = 2;
  inline int entities_size() const;
  inline void clear_entities();
  static const int kEntitiesFieldNumber = 2;
  inline const ::ige::Entity& entities(int index) const;
  inline ::ige::Entity* mutable_entities(int index);
  inline ::ige::Entity* add_entities();
  inline const ::google::protobuf::RepeatedPtrField< ::ige::Entity >&
      entities() const;
  inline ::google::protobuf::RepeatedPtrField< ::ige::Entity >*
      mutable_entities();

  // repeated .ige.Item items = 3;
  inline int items_size() const;
  inline void clear_items();
  static const int kItemsFieldNumber = 3;
  inline const ::ige::Item& items(int index) const;
  inline ::ige::Item* mutable_items(int index);
  inline ::ige::Item* add_items();
  inline const ::google::protobuf::RepeatedPtrField< ::ige::Item >&
      items() const;
  inline ::google::protobuf::RepeatedPtrField< ::ige::Item >*
      mutable_items();

  // @@protoc_insertion_point(class_scope:ige.Sync)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::ige::Geometry > geometries_;
  ::google::protobuf::RepeatedPtrField< ::ige::Entity > entities_;
  ::google::protobuf::RepeatedPtrField< ::ige::Item > items_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ige_5fsync_2eproto();
  friend void protobuf_AssignDesc_ige_5fsync_2eproto();
  friend void protobuf_ShutdownFile_ige_5fsync_2eproto();

  void InitAsDefaultInstance();
  static Sync* default_instance_;
};
// ===================================================================


// ===================================================================

// SendEpoch

// required int32 sec = 1;
inline bool SendEpoch::has_sec() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendEpoch::set_has_sec() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendEpoch::clear_has_sec() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendEpoch::clear_sec() {
  sec_ = 0;
  clear_has_sec();
}
inline ::google::protobuf::int32 SendEpoch::sec() const {
  return sec_;
}
inline void SendEpoch::set_sec(::google::protobuf::int32 value) {
  set_has_sec();
  sec_ = value;
}

// required int32 min = 2;
inline bool SendEpoch::has_min() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SendEpoch::set_has_min() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SendEpoch::clear_has_min() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SendEpoch::clear_min() {
  min_ = 0;
  clear_has_min();
}
inline ::google::protobuf::int32 SendEpoch::min() const {
  return min_;
}
inline void SendEpoch::set_min(::google::protobuf::int32 value) {
  set_has_min();
  min_ = value;
}

// required int32 hour = 3;
inline bool SendEpoch::has_hour() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SendEpoch::set_has_hour() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SendEpoch::clear_has_hour() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SendEpoch::clear_hour() {
  hour_ = 0;
  clear_has_hour();
}
inline ::google::protobuf::int32 SendEpoch::hour() const {
  return hour_;
}
inline void SendEpoch::set_hour(::google::protobuf::int32 value) {
  set_has_hour();
  hour_ = value;
}

// required int32 day = 4;
inline bool SendEpoch::has_day() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SendEpoch::set_has_day() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SendEpoch::clear_has_day() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SendEpoch::clear_day() {
  day_ = 0;
  clear_has_day();
}
inline ::google::protobuf::int32 SendEpoch::day() const {
  return day_;
}
inline void SendEpoch::set_day(::google::protobuf::int32 value) {
  set_has_day();
  day_ = value;
}

// required int32 mon = 5;
inline bool SendEpoch::has_mon() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SendEpoch::set_has_mon() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SendEpoch::clear_has_mon() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SendEpoch::clear_mon() {
  mon_ = 0;
  clear_has_mon();
}
inline ::google::protobuf::int32 SendEpoch::mon() const {
  return mon_;
}
inline void SendEpoch::set_mon(::google::protobuf::int32 value) {
  set_has_mon();
  mon_ = value;
}

// required int32 year = 6;
inline bool SendEpoch::has_year() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SendEpoch::set_has_year() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SendEpoch::clear_has_year() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SendEpoch::clear_year() {
  year_ = 0;
  clear_has_year();
}
inline ::google::protobuf::int32 SendEpoch::year() const {
  return year_;
}
inline void SendEpoch::set_year(::google::protobuf::int32 value) {
  set_has_year();
  year_ = value;
}

// -------------------------------------------------------------------

// Timestamp

// required int64 time = 1;
inline bool Timestamp::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Timestamp::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Timestamp::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Timestamp::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::int64 Timestamp::time() const {
  return time_;
}
inline void Timestamp::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// Geometry

// required int32 id = 1;
inline bool Geometry::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Geometry::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Geometry::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Geometry::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Geometry::id() const {
  return id_;
}
inline void Geometry::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 x = 2;
inline bool Geometry::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Geometry::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Geometry::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Geometry::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Geometry::x() const {
  return x_;
}
inline void Geometry::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 3;
inline bool Geometry::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Geometry::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Geometry::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Geometry::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Geometry::y() const {
  return y_;
}
inline void Geometry::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// Entity

// required int32 id = 1;
inline bool Entity::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Entity::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Entity::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Entity::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Entity::id() const {
  return id_;
}
inline void Entity::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 x = 2;
inline bool Entity::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Entity::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Entity::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Entity::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Entity::x() const {
  return x_;
}
inline void Entity::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 3;
inline bool Entity::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Entity::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Entity::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Entity::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Entity::y() const {
  return y_;
}
inline void Entity::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// Item

// required int32 id = 1;
inline bool Item::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Item::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Item::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Item::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Item::id() const {
  return id_;
}
inline void Item::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 x = 2;
inline bool Item::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Item::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Item::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Item::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Item::x() const {
  return x_;
}
inline void Item::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 3;
inline bool Item::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Item::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Item::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Item::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Item::y() const {
  return y_;
}
inline void Item::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// Sync

// repeated .ige.Geometry geometries = 1;
inline int Sync::geometries_size() const {
  return geometries_.size();
}
inline void Sync::clear_geometries() {
  geometries_.Clear();
}
inline const ::ige::Geometry& Sync::geometries(int index) const {
  return geometries_.Get(index);
}
inline ::ige::Geometry* Sync::mutable_geometries(int index) {
  return geometries_.Mutable(index);
}
inline ::ige::Geometry* Sync::add_geometries() {
  return geometries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ige::Geometry >&
Sync::geometries() const {
  return geometries_;
}
inline ::google::protobuf::RepeatedPtrField< ::ige::Geometry >*
Sync::mutable_geometries() {
  return &geometries_;
}

// repeated .ige.Entity entities = 2;
inline int Sync::entities_size() const {
  return entities_.size();
}
inline void Sync::clear_entities() {
  entities_.Clear();
}
inline const ::ige::Entity& Sync::entities(int index) const {
  return entities_.Get(index);
}
inline ::ige::Entity* Sync::mutable_entities(int index) {
  return entities_.Mutable(index);
}
inline ::ige::Entity* Sync::add_entities() {
  return entities_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ige::Entity >&
Sync::entities() const {
  return entities_;
}
inline ::google::protobuf::RepeatedPtrField< ::ige::Entity >*
Sync::mutable_entities() {
  return &entities_;
}

// repeated .ige.Item items = 3;
inline int Sync::items_size() const {
  return items_.size();
}
inline void Sync::clear_items() {
  items_.Clear();
}
inline const ::ige::Item& Sync::items(int index) const {
  return items_.Get(index);
}
inline ::ige::Item* Sync::mutable_items(int index) {
  return items_.Mutable(index);
}
inline ::ige::Item* Sync::add_items() {
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ige::Item >&
Sync::items() const {
  return items_;
}
inline ::google::protobuf::RepeatedPtrField< ::ige::Item >*
Sync::mutable_items() {
  return &items_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ige

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ige_5fsync_2eproto__INCLUDED
